theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Sales Assistant\RC\en-GB
pages: 
- 'Incoming features': 'index.md'
- 'What is Sales Assistant': 'What is Sales Assistant.md'
- 'What is the Sales Process': 'What is the Sales Process.md'
- 'What is the Follow Up': 'What is the Follow Up.md'
- 'Which are the roles of the Sales Process': 'Which are the roles of the Sales Process.md'
- 'Create a new offer': 'Create a new offer.md'
- 'Add remarks to the offer': 'Add remarks to the offer.md'
- 'Deliver an offer': 'Deliver an offer.md'
- 'Make a reservation for a Test-drive': 'Make a reservation for a Test-drive.md'
- 'Versions history': 'Versions history.md'

